spring:
  datasource:
    url: jdbc:h2:mem:sdw2023
    username: sdw2023
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
